ARDUINO_DIR  = /usr/share/arduino
ARDUINO_LIBS += OneWire DallasTemperature
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIB_PATH = /home/pi/aparduino/libraries

include /usr/share/arduino/Arduino.mk
