ARDUINO_DIR  = /usr/share/arduino
#ARDUINO_LIB_PATH = /home/pi/aparduino/libraries
USER_LIB_PATH = /home/pi/aparduino/libraries
#ARDUINO_DIR = /home/pi/aparduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

include /usr/share/arduino/Arduino.mk
